"""Reviews user_id

Revision ID: 129a58fd9ae4
Revises: 96ed247f4691
Create Date: 2019-09-21 18:14:18.809232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129a58fd9ae4'
down_revision = '96ed247f4691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
