"""Reviews user_id 2

Revision ID: 232a2acc1c6e
Revises: 129a58fd9ae4
Create Date: 2019-09-21 18:15:40.761563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232a2acc1c6e'
down_revision = '129a58fd9ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
