"""dmv table

Revision ID: 49549dbb17d5
Revises: df5be1e04e9d
Create Date: 2019-09-21 13:06:06.500251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49549dbb17d5'
down_revision = 'df5be1e04e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dmv')
    # ### end Alembic commands ###
