"""remove author

Revision ID: 4b75925c654e
Revises: 232a2acc1c6e
Create Date: 2019-09-21 18:16:24.436089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b75925c654e'
down_revision = '232a2acc1c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user_id')
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.VARCHAR(length=120), nullable=True))
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
