"""testing

Revision ID: 52d034f91568
Revises: 4b75925c654e
Create Date: 2019-09-21 18:18:39.242348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d034f91568'
down_revision = '4b75925c654e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
