"""Intructor Foreign Key 2

Revision ID: 75af391a3461
Revises: ea21a50ba591
Create Date: 2019-09-21 14:32:42.274837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75af391a3461'
down_revision = 'ea21a50ba591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('dmv_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructors', 'dmv', ['dmv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'dmv_id')
    # ### end Alembic commands ###
