"""Author of review

Revision ID: 96ed247f4691
Revises: e14fb5e3d88f
Create Date: 2019-09-21 17:10:21.814795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ed247f4691'
down_revision = 'e14fb5e3d88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###
