"""instructors table

Revision ID: 98de93361fdb
Revises: 49549dbb17d5
Create Date: 2019-09-21 13:14:58.176968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98de93361fdb'
down_revision = '49549dbb17d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instructors')
    # ### end Alembic commands ###
