"""Intructor Foreign Key

Revision ID: ea21a50ba591
Revises: 1aee9a5f3578
Create Date: 2019-09-21 14:29:34.619228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea21a50ba591'
down_revision = '1aee9a5f3578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('dmv_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'instructors', 'dmv', ['dmv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'dmv_id')
    # ### end Alembic commands ###
